from enum import Enum


class JobStatus(str, Enum):
    IN_QUEUE = "IN_QUEUE"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"


class EndpointStatus(str, Enum):
    DEPLOYING = "DEPLOYING"
    READY = "READY"
    UNHEALTHY = "UNHEALTHY"


class PodStatus(str, Enum):
    RUNNING = "RUNNING"
    STOPPED = "STOPPED"
    TERMINATED = "TERMINATED"


class NotificationType(str, Enum):
    JOB_SUBMITTED = "JOB_SUBMITTED"
    JOB_CANCELED = "JOB_CANCELED"
    JOB_TIMED_OUT = "JOB_TIMED_OUT"

    CREATE_ENDPOINT = "CREATE_ENDPOINT"
    UPDATE_ENDPOINT = "UPDATE_ENDPOINT"
    DELETE_ENDPOINT = "DELETE_ENDPOINT"

    CREATE_POD = "CREATE_POD"
    UPDATE_POD = "UPDATE_POD"
    START_POD = "START_POD"
    STOP_POD = "STOP_POD"
    DELETE_POD = "DELETE_POD"

    CREATE_VOLUME = "CREATE_VOLUME"
    UPDATE_VOLUME = "UPDATE_VOLUME"
    MOUNT_VOLUME = "MOUNT_VOLUME"
    UNMOUNT_VOLUME = "UNMOUNT_VOLUME"


class EntityKind(str, Enum):
    JOB = "JOB"
    ENDPOINT = "ENDPOINT"
    POD = "POD"
    VOLUME = "VOLUME"
