from enum import Enum


class JobStatus(str, Enum):
    IN_QUEUE = "IN_QUEUE"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"


class EndpointStatus(str, Enum):
    DEPLOYING = "DEPLOYING"
    READY = "READY"
    UNHEALTHY = "UNHEALTHY"


class PodStatus(str, Enum):
    RUNNING = "RUNNING"
    STOPPED = "STOPPED"
    TERMINATED = "TERMINATED"


class NotificationType(str, Enum):
    JOB_CHANGED = "JOB_CHANGED"
    
    ENDPOINT_CHANGED = "ENDPOINT_CHANGED"
    ENDPOINT_DELETED = "ENDPOINT_DELETED"

    POD_STATUS_CHANGED = "POD_STATUS_CHANGED"
    POD_TERMINATED = "POD_TERMINATED"

    VOLUME_CHANGED = "VOLUME_CHANGED"
    VOLUME_DELETED = "VOLUME_DELETED"

    VOLUME_MOUNTED = "VOLUME_MOUNTED"
    VOLUME_UNMOUNTED = "VOLUME_UNMOUNTED"


class EntityKind(str, Enum):
    JOB = "JOB"
    ENDPOINT = "ENDPOINT"
    POD = "POD"
    VOLUME = "VOLUME"
